In [1]:
import numpy as np

### Single dimensionArray 

In [47]:
ls1 = [4,5,6,4,5]

In [50]:
arr1 = np.array(ls1)

In [48]:
ls1.sort()

In [49]:
ls1

[4, 4, 5, 5, 6]

In [51]:
arr1.sort()

In [52]:
arr1

array([4, 4, 5, 5, 6])

In [55]:
len(ls1)

5

In [57]:
len(arr1)

5

In [59]:
x = sum(ls1)

In [60]:
x

24

In [61]:
y = sum(arr1)

In [62]:
y

24

In [65]:
from statistics import mean
ml = mean(ls1)
ml

4.8

In [72]:
al = arr1.mean()
al

4.8

__Just for testing__

In [74]:
mt = mean(arr1)
mt

4

In [69]:
arr1

array([4, 4, 5, 5, 6])

In [71]:
arr1.ndim

1

## Multidimension Array

In [120]:
ls2 = [[23,np.nan,np.nan,87,2,3],[34,78,np.nan,3,46,24],[56,28,np.nan,4,43,40]]
ls2

[[23, nan, nan, 87, 2, 3], [34, 78, nan, 3, 46, 24], [56, 28, nan, 4, 43, 40]]

In [121]:
arr2 = np.array(ls2)
arr2

array([[23., nan, nan, 87.,  2.,  3.],
       [34., 78., nan,  3., 46., 24.],
       [56., 28., nan,  4., 43., 40.]])

In [122]:
arr2.shape

(3, 6)

In [123]:
arr2.ndim

2

In [124]:
arr2.dtype

dtype('float64')

In [125]:
arr3 = arr2

In [126]:
arr3 

array([[23., nan, nan, 87.,  2.,  3.],
       [34., 78., nan,  3., 46., 24.],
       [56., 28., nan,  4., 43., 40.]])

In [127]:
arr2

array([[23., nan, nan, 87.,  2.,  3.],
       [34., 78., nan,  3., 46., 24.],
       [56., 28., nan,  4., 43., 40.]])

In [139]:
arr2

array([[23., nan, nan, 87.,  2.,  3.],
       [34., 78., nan,  3., 46., 24.],
       [56., 28., nan,  4., 43., 40.]])

In [142]:
arr2m = np.nanmean(arr2)

In [143]:
arr2m

33.642857142857146

In [150]:
arr2min = np.nanmin(arr2) 

In [151]:
arr2min

2.0

In [132]:
ls5 = [[23,94,89,87,2,3],[34,78,90,3,46,24],[56,28,55,49,43,40]]

In [134]:
arr5 = np.array(ls5)
arr5

array([[23, 94, 89, 87,  2,  3],
       [34, 78, 90,  3, 46, 24],
       [56, 28, 55, 49, 43, 40]])

In [136]:
arr5m = arr5.mean()
arr5m

46.888888888888886

In [138]:
arr5.shape

(3, 6)

In [165]:
m1a5 = np.nanmean(arr5, axis=1)
m1a5

array([49.66666667, 45.83333333, 45.16666667])

In [152]:
 m3mean = np.nanmean(arr2, axis=0)

array([[23., nan, nan, 87.,  2.,  3.],
       [34., 78., nan,  3., 46., 24.],
       [56., 28., nan,  4., 43., 40.]])

In [166]:
 m3mean = np.nanmean(arr2, axis=0)

C:\Users\edwin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: Mean of empty slice
  """Entry point for launching an IPython kernel.


In [167]:
m3mean

array([37.66666667, 53.        ,         nan, 31.33333333, 30.33333333,
       22.33333333])

In [163]:
m1 = np.nanmean(arr2, axis=1)

In [158]:
m1

array([28.75, 37.  , 34.2 ])

In [159]:
arr2

array([[23., nan, nan, 87.,  2.,  3.],
       [34., 78., nan,  3., 46., 24.],
       [56., 28., nan,  4., 43., 40.]])

In [168]:
arr2

array([[23., nan, nan, 87.,  2.,  3.],
       [34., 78., nan,  3., 46., 24.],
       [56., 28., nan,  4., 43., 40.]])

In [170]:
arr2.shape

(3, 6)

In [174]:
em = np.nanmean(arr2)
em

33.642857142857146

In [175]:
arr2

array([[23., nan, nan, 87.,  2.,  3.],
       [34., 78., nan,  3., 46., 24.],
       [56., 28., nan,  4., 43., 40.]])

In [176]:
m3mean = np.nanmean(arr2,axis=0)
m3mean

C:\Users\edwin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: Mean of empty slice
  """Entry point for launching an IPython kernel.


array([37.66666667, 53.        ,         nan, 31.33333333, 30.33333333,
       22.33333333])

In [177]:
m3mean = np.nanmean(arr2,axis=1)
m3mean

array([28.75, 37.  , 34.2 ])

In [181]:
arr2

array([[23., nan, nan, 87.,  2.,  3.],
       [34., 78., nan,  3., 46., 24.],
       [56., 28., nan,  4., 43., 40.]])

In [187]:
arrlog = np.isnan(arr2)

In [184]:
arr2[arrlog] = 0

In [186]:
arr2

array([[23.,  0.,  0., 87.,  2.,  3.],
       [34., 78.,  0.,  3., 46., 24.],
       [56., 28.,  0.,  4., 43., 40.]])

In [192]:
arr2[0,3]

87.0

In [193]:
arr3

array([[23.,  0.,  0., 87.,  2.,  3.],
       [34., 78.,  0.,  3., 46., 24.],
       [56., 28.,  0.,  4., 43., 40.]])

In [194]:
arr2

array([[23.,  0.,  0., 87.,  2.,  3.],
       [34., 78.,  0.,  3., 46., 24.],
       [56., 28.,  0.,  4., 43., 40.]])

In [195]:
 arr4 = arr2

In [201]:
arr6 = arr2.copy

In [199]:
print(type(arr2))

<class 'numpy.ndarray'>


In [200]:
print(type(arr4))

<class 'numpy.ndarray'>


In [196]:
arr4

array([[23.,  0.,  0., 87.,  2.,  3.],
       [34., 78.,  0.,  3., 46., 24.],
       [56., 28.,  0.,  4., 43., 40.]])

In [197]:
arr2

array([[23.,  0.,  0., 87.,  2.,  3.],
       [34., 78.,  0.,  3., 46., 24.],
       [56., 28.,  0.,  4., 43., 40.]])

In [ ]:
!conda update conda